import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";

import ReactQueryProvider from "@/components/provider/query_client";
import { AuthProvider } from "@/utils/context/auth_context";
import { FirebaseTrackingProvider } from "@/components/provider/FirebaseTrackingProvider";
import { UnreadProvider } from "@/utils/context/UnreadContext";
import { Toaster } from "sonner";
import OneSignalProvider from "@/components/OneSignalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AGPAII Digital",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-6MTB31ZE0G"
        />
        <Script
          id="ga"
          strategy="afterInteractive"
        >{`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-6MTB31ZE0G');
        `}</Script>
      </head>

      <body className={inter.className}>
        <OneSignalProvider />

        <SpeedInsights />
        <Analytics />

        <ReactQueryProvider>
          <AuthProvider>
            <UnreadProvider>
              <FirebaseTrackingProvider>
                {children}
              </FirebaseTrackingProvider>
            </UnreadProvider>
          </AuthProvider>
        </ReactQueryProvider>

        <Toaster
          position="top-center"
          richColors
          duration={2000}
        />
      </body>
    </html>
  );
}
